name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Executar o docker build"
      - run: echo "Enviar imagem Docker para o Docker Hub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Configurar o kubeconfig"
      - run: echo "Executar o apply"
